### ISSUE TITLE
Not working in version > 1.6

### ISSUE THREAD

**Issue by juanesarango** [AntonioCuevaUrraco/nativescript-facebook-login#18]
After version 1.6 of Nativescript, a local `androidmanifest.xml` for Android and `Info.plist`for iOS was added in the `app_resources` so that any changes would be preserved when you do a `platform remove android`. So the necessary code that should be inserted shouldn't be in `platforms/…` because it gets overwritten, but in  `App_Resources/...`

Anyway I was going to help changing this with PR for documentation, but even changing this, this plugin doesn't seem to work: In Android case it doesn't recognize this changes in App_Resources neither:

```
com.tns.NativeScriptException: 
Calling js method onClick failed

Error: Log in attempt failed: FacebookActivity could not be started. Please make sure you added FacebookActivity to the AndroidManifest.
    com.facebook.login.LoginManager.startLogin(LoginManager.java:369)
    com.facebook.login.LoginManager.logInWithPublishPermissions(LoginManager.java:287)
    com.tns.Platform.callJSMethodNative(Native Method)
    com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
    com.tns.Platform.callJSMethod(Platform.java:715)
    com.tns.Platform.callJSMethod(Platform.java:694)
    com.tns.Platform.callJSMethod(Platform.java:684)
    com.tns.gen.android.view.View_OnClickListener_ftns_modules_ui_button_button_l19_c42__.onClick(android.view.View$OnClickListener.java)
    android.view.View.performClick(View.java:4780)
    android.view.View$PerformClick.run(View.java:19866)
    android.os.Handler.handleCallback(Handler.java:739)
    android.os.Handler.dispatchMessage(Handler.java:95)
    android.os.Looper.loo
```

**Comment by AntonioCuevaUrraco** [comment]
Hello @juanesarango It is true that now it is possible to put a manifest and plist on the app_resources folder do override the one in the platform I will update the plugin once all the discussions are over https://github.com/NativeScript/android-runtime/issues/369

Anyway I  am running this plugin on 1.6 with no problem for android and iOS. Sometimes the plugins doesn't plug so well, Make sure the final manifest contains the facebook activity, you can test to remove the manifest on app_resources and write the facebook activity in platform after tns prepare android (otherwise it will get replaced when it detect new plugins)

**Comment by AntonioCuevaUrraco** [comment]
@juanesarango open this issue again if you need help
