### ISSUE TITLE
Unable to find iOS Api's when trying to implement this plugin using angular 2 and typescript

### ISSUE THREAD

**Issue by yogeshwar607** [AntonioCuevaUrraco/nativescript-facebook-login#20]
<img width="1280" alt="screen shot 2016-06-14 at 3 19 33 am" src="https://cloud.githubusercontent.com/assets/10059011/16024325/da4aed5e-31de-11e6-89d5-5a93a7d56a02.png">

**Comment by AntonioCuevaUrraco** [comment]
I have done 0 work on NS + Angular 2 so I can not help you much about it.  
Have you check other plugins that use cocoapods to see if they can access the native API? maybe with Angular you have to use a different naming to access them instead of directly as it is use on the plugin.  
Also I when NS was starting with the cocoapods they had some problems with the same and it was because they were not added correctly to fix it we had to remove and add the platform so the native API is detected.   

Other than that, create an issue on NS+Angular project and see if they have some idea :-/

**Comment by fasilpv** [comment]
Declare variables like this

declare class UIResponder {};
declare class UIApplicationDelegate{};
declare class FBSDKApplicationDelegate {
    static sharedInstance():any;
};

declare class FBSDKAppEvents{
    static activateApp();
};
declare class UIApplication {};
declare class NSDictionary {};

**Comment by LSmint** [comment]
After declare variables, i still get this error: Can't find variable: FBSDKApplicationDelegate
