### ISSUE TITLE
Android crashing

### ISSUE THREAD

**Issue by jlooper** [AntonioCuevaUrraco/nativescript-facebook-login#4]
hi, Sorry for the flurry of issues. I'm unable to get the Facebook plugin to initialize for Android. The following error crops up:

TypeError: Cannot read property 'FacebookSdk' of undefined
File: "/data/data/com.ladeezfirstmedia.ThisOrThat/files/app/tns_modules/nativescript-facebook-login/facebook-handler.js line: 9 column:16

Not sure what's going on here!

thanks,
Jen

**Comment by AntonioCuevaUrraco** [comment]
Sometimes the .aar library with the sdk for android don't get linked to the platform after installing the plugin. In a few words android can not find .aar library and this end up in the error:  
TypeError: Cannot read property 'FacebookSdk' of undefined
File: "/data/data/com.ladeezfirstmedia.ThisOrThat/files/app/tns_modules/nativescript-facebook-login/facebook-handler.js line: 9 column:16   

As a workarround for now till the cause is found you can add the facebook sdk dependency manually by changing the build.gradle (platforms/android/build.gradle) like so:

```
dependencies {
    ....
        ....
    compile "com.android.support:support-v4:$suppotVer"
    compile "com.android.support:appcompat-v7:$suppotVer"

    //Facebook sdk
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
        ....
        ....

}
```

**Comment by thedanielhanke** [comment]
same here - even after adding the line to build.gradle.

**Comment by thedanielhanke** [comment]
okay - i used livesync --watch. after using `run android` it went well. maybe this info should be added to the doc? best regards

**Comment by AntonioCuevaUrraco** [comment]
This error means that the plugin didn't plug. Is the native library what is undefined. I have noticed with all the plugins that the platform sometimes doesn't get the libraries exposes. I can only suggest to remove the plugin, remove the platform, add the plugin and add the platform in that order : -/  hope it starts working after that

**Comment by AntonioCuevaUrraco** [comment]
Added to the doc
